// Tabaqa PD-model validation results on real default data (Berka / PKDD'99).
// Single source of truth for the in-app "Model validation" panel — mirrors
// eval/DATA_REPORT.md, generated by eval/berka_train.py against the public CTU
// "Financial" dataset (https://relational.fel.cvut.cz/dataset/Financial).
// Update both files together if the model is re-trained.

export interface ScoreBand {
  band: number
  accounts: number
  defaults: number
  rate: number
}

export interface FeatureIV {
  key: string
  iv: number
}

export interface ValidationData {
  dataset: string
  datasetUrl: string
  accounts: number
  defaults: number
  badRate: number
  holdout: { auc: number; ks: number }
  cv: { auc: number; ks: number }
  bands: ScoreBand[]
  features: FeatureIV[]
}

export const VALIDATION: ValidationData = {
  dataset: 'Berka · PKDD’99',
  datasetUrl: 'https://relational.fel.cvut.cz/dataset/Financial',
  accounts: 682,
  defaults: 76,
  badRate: 0.111,
  holdout: { auc: 0.89, ks: 0.683 },
  cv: { auc: 0.858, ks: 0.562 },
  // default rate by score quintile — should fall monotonically as score rises
  bands: [
    { band: 1, accounts: 137, defaults: 53, rate: 0.387 },
    { band: 2, accounts: 136, defaults: 14, rate: 0.103 },
    { band: 3, accounts: 136, defaults: 4, rate: 0.029 },
    { band: 4, accounts: 136, defaults: 5, rate: 0.037 },
    { band: 5, accounts: 137, defaults: 0, rate: 0.0 },
  ],
  // per-feature predictive strength (WOE Information Value)
  features: [
    { key: 'balance_volatility', iv: 1.295 },
    { key: 'income_regularity', iv: 0.442 },
    { key: 'recurring_obligation_load', iv: 0.318 },
    { key: 'min_balance', iv: 0.317 },
    { key: 'income_expense_ratio', iv: 0.3 },
    { key: 'avg_balance', iv: 0.244 },
    { key: 'nsf_count', iv: 0.0 },
  ],
}
